# Generated by Django 4.2.4 on 2023-08-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        default="media\\call-default.png", upload_to="Emergency-logo"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="policeStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="polices-stations")),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=2000)),
                ("city", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Commissioner", "Commissioner"),
                            ("Citizen", "Citizen"),
                            ("Inspector", "Inspector"),
                            ("SubInspector", "SubInspector"),
                            ("Constable", "Constable"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("complaint_msg", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Done", "Done"),
                            ("Pending", "Pending"),
                            ("Continue", "Continue"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
            ],
        ),
    ]
